---
director_uuid: 337b329b-3b64-4995-90e9-65094ae19027
name: cf-173
releases:
  - name: cf
    version: latest

meta:
  stemcell:
    name: bosh-openstack-kvm-ubuntu
    version: latest

properties:
  domain: 69.36.245.71.xip.io
  secret: steelmouse88

  use_protocol: http
  use_nossl: false

  nats:
    user: nats
    password: nats

  uaa_client_auth_credentials:
    username: services
    password: (( properties.secret ))

  databases: &databases
    roles:
      - tag: admin
        name: ccadmin
        password: ccadmin
      - tag: admin
        name: uaaadmin
        password: uaaadmin

  ccdb: &ccdb
    roles:
      - tag: admin
        name: ccadmin
        password: ccadmin

  ccdb_ng: 
    roles:
      - tag: admin
        name: ccadmin
        password: ccadmin

  loggregator:
    nats:
      password: (( properties.nats.password ))

  uaadb:
    roles:
      - tag: admin
        name: uaaadmin
        password: uaaadmin

  router: 
    status:
      user: router
      password: (( properties.secret ))

  dea_next:
    disk_mb: 10000
    memory_mb: 7096

  loggregator_endpoint: # The end point sources will connect to
    shared_secret: (( properties.secret ))

  cc: &cc
    logging_level: debug
    cc_partition: default
    db_encryption_key: (( properties.secret ))
    bootstrap_admin_email: "info@nebulaworks.com"
    bulk_api_password: (( secret ))
    uaa_resource_id: cloud_controller
    staging_upload_user: upload
    staging_upload_password: (( properties.secret ))
    resource_pool:
      resource_directory_key: cf-att-io-cc-resources
    droplets:
      droplet_directory_key: cf-att-io-cc-droplets
    packages:
      app_package_directory_key: cf-att-io-cc-packages
    buildpacks:
      buildpack_directory_key: cf-att-io-cc-buildpacks

  login:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    uaa_certificate: |
        -----BEGIN CERTIFICATE-----
        MIIDtTCCAx6gAwIBAgIJANTsZDRp8cyeMA0GCSqGSIb3DQEBBQUAMIGZMQswCQYD
        VQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEXMBUGA1UEBxMOQ29yb25hIGRl
        bCBNYXIxFDASBgNVBAoTC05lYnVsYXdvcmtzMQswCQYDVQQLEwJJVDEUMBIGA1UE
        AxMLTmVidWxhd29ya3MxIzAhBgkqhkiG9w0BCQEWFGluZm9AbmVidWxhd29ya3Mu
        Y29tMB4XDTE0MDgwMTE5MDQ1NVoXDTE1MDgwMTE5MDQ1NVowgZkxCzAJBgNVBAYT
        AlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRcwFQYDVQQHEw5Db3JvbmEgZGVsIE1h
        cjEUMBIGA1UEChMLTmVidWxhd29ya3MxCzAJBgNVBAsTAklUMRQwEgYDVQQDEwtO
        ZWJ1bGF3b3JrczEjMCEGCSqGSIb3DQEJARYUaW5mb0BuZWJ1bGF3b3Jrcy5jb20w
        gZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAKpXTrQgPT8GLvfjk4/xh8xd1HZ3
        EVbpvuc6dk1sq3yPGZiwpWIhfcSYob2ScfZbKmamUBII3dDSbr4hL24KT4L/ApF0
        JDhYbMRJ2DR4/evzqDxs/29PdE7TGRvRybwtezd1a0Yx8QeI3YRC+dTJZ/OOJeYv
        JnwQgoI/n1e4d2FNAgMBAAGjggEBMIH+MB0GA1UdDgQWBBSEHRAJDTiL6VmXUZ+3
        1QYyUO8hmTCBzgYDVR0jBIHGMIHDgBSEHRAJDTiL6VmXUZ+31QYyUO8hmaGBn6SB
        nDCBmTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFzAVBgNVBAcT
        DkNvcm9uYSBkZWwgTWFyMRQwEgYDVQQKEwtOZWJ1bGF3b3JrczELMAkGA1UECxMC
        SVQxFDASBgNVBAMTC05lYnVsYXdvcmtzMSMwIQYJKoZIhvcNAQkBFhRpbmZvQG5l
        YnVsYXdvcmtzLmNvbYIJANTsZDRp8cyeMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcN
        AQEFBQADgYEAVPJEEErPGOawy03PdStUwoBwFDbKDYno1Hh58e23UufkHUFjFoC/
        tF0J3/Mw1wBRcdFrEJrJQ0gfOVKz8rbyGFkBHwafB8bCBo16sYitJEyQnyKSqBR1
        z96KRmcNzYmlbiSdKHSf61sxXCvGEwDkqKcfbKghZsAt9cpvg+k4tq0=
        -----END CERTIFICATE-----

  uaa:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    resource_id: account_manager
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: (( properties.secret ))
    admin:
      client_secret: (( properties.secret ))
    batch:
      username: batch
      password: (( properties.secret ))
    clients:
      login:
        secret: (( properties.secret ))
      developer_console:
        secret: (( properties.secret ))
      app-direct:
        secret: (( properties.secret ))
      support-services:
        secret: (( properties.secret ))
      servicesmgmt:
        secret: (( properties.secret ))
      space-mail:
        secret: (( properties.secret ))
    scim:
      user:
         override: true
      userids_enabled: true      
      users:
      - (( "admin|" properties.secret "|scim.write,scim.read,openid,cloud_controller.admin,uaa.admin,password.write"))
      - (( "services|" properties.secret "|scim.write,scim.read,openid,cloud_controller.admin")) 